/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.core;

import java.awt.BorderLayout;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.Marker;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.time.Day;
import org.jfree.data.time.RegularTimePeriod;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.ui.RectangleAnchor;
import org.jfree.ui.TextAnchor;
import static system.core.Login.db;
import system.helper.Helper;
import system.model.SalesReportBean;
import system.utility.ConnectionUtil;
import system.utility.DateReturn;

/**
 *
 * @author JANSEN
 */
public class Sales extends javax.swing.JPanel {

   public static Connection con = ConnectionUtil.getDBConnection(db);
   final SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
    ArrayList<SalesReportBean> list = new ArrayList<>();
 //  SalesReportBean spb;
 //  final TimeSeriesCollection dataset = createDataset("Sales");
 //  final JFreeChart chart = ChartFactory.createTimeSeriesChart(
  //          "Sales Report Chart", "Time", "Value", dataset, true, true, false
 //       );
   
    public Sales() {
        initComponents();
        String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, "
            + "StockOut.Total, Stockout.Date from " +
            "Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId";
            String query = "Select distinct(DATEADD(dd, DATEDIFF(dd, 0, date), 0)) as date from StockOut";

            setTable(normal, query);
            createLineChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        total = new javax.swing.JLabel();
        category = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fromDate = new com.toedter.calendar.JDateChooser();
        fromText = new javax.swing.JLabel();
        toText = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        stable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setText("TOTAL:");

        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Daily", "Monthly", "Yearly", " " }));
        category.setOpaque(false);
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Time Period:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromDatePropertyChange(evt);
            }
        });

        fromText.setText("From:");

        toText.setText("To:");

        toDate.setDateFormatString("yyyy-MM-dd");
        toDate.setMinSelectableDate(new java.util.Date(978282066000L));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fromText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fromDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fromDate.getDateEditor().addPropertyChangeListener(
            new PropertyChangeListener() {
                @Override
                public void propertyChange(PropertyChangeEvent e) {
                    if ("date".equals(e.getPropertyName())) {
                        if(fromDate.getDate() != null && toDate.getDate() != null){
                            Date fdate = fromDate.getDate();
                            Date tdate = toDate.getDate();
                            String fromSplit[] =  DateFormat.getInstance()
                            .format(fdate).split("\\s+");
                            String toSplit[] =  DateFormat.getInstance()
                            .format(tdate).split("\\s+");
                            String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, "
                            + "StockOut.Total, Stockout.Date from " +
                            "Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId where "
                            + "cast(StockOut.date as Date) between '"+fromSplit[0]+"' and '"+toSplit[0]+"' ";
                            String query = "Select distinct(DATEADD(dd, DATEDIFF(dd, 0, date), 0)) as date "
                            + "from StockOut where cast(StockOut.date as date) between '"+fromSplit[0]+"' and"
                            + " '"+toSplit[0]+"' ";

                            setTable(normal, query);
                        }

                    }
                }
            });
            this.add(fromDate);
            toDate.getDateEditor().addPropertyChangeListener(
                new PropertyChangeListener() {
                    @Override
                    public void propertyChange(PropertyChangeEvent e) {
                        if ("date".equals(e.getPropertyName())) {
                            if(fromDate.getDate() != null && toDate.getDate() != null){
                                Date fdate = fromDate.getDate();
                                Date tdate = toDate.getDate();
                                String[] fromSplit =  DateFormat.getInstance()
                                .format(fdate).split("\\s+");
                                String[] toSplit =  DateFormat.getInstance()
                                .format(tdate).split("\\s+");
                                String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, "
                                + "StockOut.Total, Stockout.Date from " +
                                "Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId where "
                                + "cast(StockOut.date as Date) between '"+fromSplit[0]+"' and '"+toSplit[0]+"' ";
                                String query = "Select distinct(DATEADD(dd, DATEDIFF(dd, 0, date), 0)) as date "
                                + "from StockOut where cast(StockOut.date as date) between '"+fromSplit[0]+"' and"
                                + " '"+toSplit[0]+"' ";

                                setTable(normal, query);
                            }

                        }
                    }
                });
                this.add(toDate);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                stable.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                    },
                    new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                    }
                ));
                jScrollPane1.setViewportView(stable);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Report", jPanel1);

                jPanel5.setBackground(new java.awt.Color(255, 255, 255));

                panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
                panel2.setLayout(panel2Layout);
                panel2Layout.setHorizontalGroup(
                    panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 459, Short.MAX_VALUE)
                );
                panel2Layout.setVerticalGroup(
                    panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 338, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 286, Short.MAX_VALUE))
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(210, Short.MAX_VALUE))
                );

                jTabbedPane1.addTab("Forecast", jPanel5);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                );
            }// </editor-fold>//GEN-END:initComponents

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        if(category.getSelectedIndex() == 1){
            setTableforMonth();
        }

        if(category.getSelectedIndex() == 2){
            setTableforYear();
        }

        if(category.getSelectedIndex() == 0){
            String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, "
            + "StockOut.Total, Stockout.Date from " +
            "Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId";
            String query = "Select distinct(DATEADD(dd, DATEDIFF(dd, 0, date), 0)) as date from StockOut";

            setTable(normal, query);
        }
    }//GEN-LAST:event_categoryActionPerformed

    private void fromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromDatePropertyChange

    }//GEN-LAST:event_fromDatePropertyChange
    public void createLineChart(){
          XYPlot plot;
        TimeSeriesCollection dataset = createDataset("Sales");

        JFreeChart chart = ChartFactory.createTimeSeriesChart(
            "Sales Report Chart", "Date", "Value", dataset, true, true, false
        );
        
        plot = chart.getXYPlot();
        plot.setBackgroundPaint(Color.lightGray);
        plot.setDomainGridlinePaint(Color.white);
        plot.setRangeGridlinePaint(Color.white);
//        this.plot.setAxisOffset(new Spacer(Spacer.ABSOLUTE, 4, 4, 4, 4));
         ValueAxis axis = plot.getDomainAxis();
        axis.setAutoRange(true);

        NumberAxis rangeAxis2 = new NumberAxis("Range Axis 2");
        rangeAxis2.setAutoRangeIncludesZero(false);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        panel2.setSize(500, 400);
        chartPanel.setPreferredSize(panel2.getSize());
        chartPanel.setVisible(true);
        panel2.setLayout(new java.awt.BorderLayout());
        panel2.add(chartPanel, BorderLayout.CENTER);
        panel2.setVisible(true);
        
        panel2.validate();
        //   ChartFrame frame = new ChartFrame("Bar chart for melrose", chart);
        //    frame.setVisible(true);
        //     frame.setSize(450, 350);
    }  
    
    private TimeSeriesCollection createDataset(final String name) {
        final TimeSeries series = new TimeSeries(name);
          
            Iterator iter = list.iterator();
            RegularTimePeriod t; // dd, MM, YYYY
     
            while (iter.hasNext()) {
                SalesReportBean sp = (SalesReportBean)iter.next(); //yyyy-mm-dd
                String date[] = sp.getDate().split("-");
                t = new Day( Integer.parseInt(date[2]), Integer.parseInt(date[1]), Integer.parseInt(date[0]) );
                series.add(t, sp.getValue());
            }
            return new TimeSeriesCollection(series);
    }
    
    //Sets the table to the default period's specifications
    public void setTable(String normal, String query){ 
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        
        
        model.setColumnIdentifiers(new Object[]{"Date", "Total Items Sold", "Sales", "Costs", "Profits"});
        ResultSet rs = Helper.getData(con, query);
        String outer[];
        String inner[];
        int qty = 0; //Pertains to Total Items Sold
        float costs = 0, sales = 0, profits = 0; 

        Object[] row = new Object[5];
         try {
             while(rs.next()){
                 outer = rs.getTimestamp("date").toString().split("\\s+");
                 row[0] = outer[0]; // sets Date into row 1 of JTable, outer[0] is the date in yyyy-mm-dd format
                 
                 ResultSet rs2 = Helper.getData(con, normal);
                 while(rs2.next()){
                     inner = rs2.getTimestamp("Date").toString().split("\\s+");
                     if(outer[0].equals(inner[0])){ //check whether the date in outer sql is equal to date in inner sql
                         qty += rs2.getInt("Quantity");
                         costs += rs2.getInt("Quantity") * rs2.getFloat("Cost");
                         sales += rs2.getInt("Quantity") * rs2.getFloat("SellPrice");
                         profits += rs2.getInt("Quantity") * ( rs2.getFloat("SellPrice") - rs2.getFloat("Cost") );                         
                     }
                 }
                  row[1] = qty; // sets the quantity in row 2 of jtable
                  row[2] = "₱ " + sales; //sales 
                  row[3] = "₱ " + costs; //costs
                  row[4] = "₱ " +profits; //profits
                  SalesReportBean spb = new SalesReportBean(sales, outer[0]);
                  list.add(spb);
                  
                  qty = 0; costs = 0; sales = 0; profits = 0; //resets the values
                  model.addRow(row); // add to row
             }
             
             stable.setModel(model);
             total.setText("TOTAL: " + model.getRowCount());
         } catch (SQLException ex) {
             Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
         }
           
    }
    
    public void setTableforMonth(){
         DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        String query = "Select distinct(MONTH(StockOut.Date)) as Month, Year(StockOut.Date) as Year from StockOut";
        String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, " +
                        " StockOut.Total, MONTH(StockOut.date) as Month, YEAR(StockOut.date) as Year from  " +
                        " Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId ";
        model.setColumnIdentifiers(new Object[]{"Date", "Total Items Sold", "Sales", "Costs", "Profits"});
        ResultSet rs = Helper.getData(con, query);
       
        int qty = 0; //Pertains to Total Items Sold
        float costs = 0, sales = 0, profits = 0; 

        Object[] row = new Object[5];
         try {
             while(rs.next()){          
                 row[0] = DateReturn.formatMonth(rs.getString("Month")) + rs.getString("Year");
                 ResultSet rs2 = Helper.getData(con, normal);
                 while(rs2.next()){

                     if(rs.getString("Month").equals(rs2.getString("Month")) &&
                             rs.getString("Year").equals(rs2.getString("Year"))){
                         System.out.println("OMFG it connects");
                         qty += rs2.getInt("Quantity");
                         costs += rs2.getInt("Quantity") * rs2.getFloat("Cost");
                         sales += rs2.getInt("Quantity") * rs2.getFloat("SellPrice");
                         profits += rs2.getInt("Quantity") * ( rs2.getFloat("SellPrice") - rs2.getFloat("Cost") );                         
                     }
                 }
                  row[1] = qty;
                  row[2] = "₱ " + sales;
                  row[3] = "₱ " + costs;
                  row[4] = "₱ " +profits;
                  qty = 0; costs = 0; sales = 0; profits = 0;
                  model.addRow(row);
             }
             
             stable.setModel(model);
         } catch (SQLException ex) {
             Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public void setTableforYear(){
          DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int rowIndex, int mColIndex) {
                return false;
            }
        };
        String query = "Select distinct(Year(StockOut.Date)) as Year from StockOut";
        String normal = "Select Warehouse.ProductName, StockOut.Quantity, WareHouse.Cost, StockOut.SellPrice, " +
                        " StockOut.Total, YEAR(StockOut.Date) as Year from  " +
                        " Warehouse inner join StockOut on Warehouse.ProductId = StockOut.ProductId ";
        model.setColumnIdentifiers(new Object[]{"Date", "Total Items Sold", "Sales", "Costs", "Profits"});
        ResultSet rs = Helper.getData(con, query);
       
        int qty = 0; //Pertains to Total Items Sold
        float costs = 0, sales = 0, profits = 0; 

        Object[] row = new Object[5];
         try {
             while(rs.next()){          
                 row[0] = rs.getString("Year");
                 ResultSet rs2 = Helper.getData(con, normal);
                 while(rs2.next()){

                     if(rs.getString("Year").equals(rs2.getString("Year"))){
                         System.out.println("OMFG it connects");
                         qty += rs2.getInt("Quantity");
                         costs += rs2.getInt("Quantity") * rs2.getFloat("Cost");
                         sales += rs2.getInt("Quantity") * rs2.getFloat("SellPrice");
                         profits += rs2.getInt("Quantity") * ( rs2.getFloat("SellPrice") - rs2.getFloat("Cost") );                         
                     }
                 }
                  row[1] = qty;
                  row[2] = "₱ " + sales;
                  row[3] = "₱ " + costs;
                  row[4] = "₱ " +profits;
                  qty = 0; costs = 0; sales = 0; profits = 0;
                  model.addRow(row);
             }
             
             stable.setModel(model);
         } catch (SQLException ex) {
             Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
  
    public float[] computeForDay(String query){
      
        ResultSet rs = Helper.getData(con, query);
         try {
               float quantity = 0;
               float costs = 0;
               float profit = 0;
               float sales = 0;
             while(rs.next()){
                 quantity += rs.getInt("Quantity");
                 costs += rs.getInt("Quantity") * rs.getFloat("Cost");
                 sales += rs.getFloat("Total");
                 profit += rs.getFloat("Total") - ( rs.getInt("Quantity") * rs.getFloat("Quantity")  );
                 
             }
               return new float[]{(int)quantity, costs, sales, profit};
         
         } catch (SQLException ex) {
             Logger.getLogger(SalesReport.class.getName()).log(Level.SEVERE, null, ex);
         }
         
         
        return null;
      
    }
   
    //refresh: remove all the components, then revalidate and repaint, then start over again.
     public void refresh(){
        removeAll();
        revalidate();
        repaint();
        initComponents();
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox category;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel fromText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTable stable;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JLabel toText;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
